watchingItems = ['Dragon hunter crossbow',
"Zulrah's scales",
'Twisted bow',
'Kodai wand',
'Ghrazi rapier',
'Dragon claws',
'Armadyl chainskirt',
'Armadyl chestplate',
"Viggora's chainmace (u)",
"Craw's bow (u)",
'Zenyte shard',
'Elder maul',
'Avernic defender hilt',
'Abyssal bludgeon',
'Armadyl crossbow',
'Saradomin godsword',
'Dragonfire ward',
'Imbued heart',
'Elysian spirit shield',
'Sanguinesti staff (uncharged)',
'Arcane spirit shield',
'Ancestral robe top',
'Ancestral robe bottom',
'Dragon warhammer',
'Justiciar faceguard',
'Justiciar legguards',
'Justiciar chestguard',
'Ranger boots',
'Pegasian boots',
'Bandos tassets',
'Primordial boots',
'Ancient wyvern shield',
'Amulet of eternal glory',
'Dragon crossbow',
'Cannonballs',
'Blood rune',
'Death rune'
]
